// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlkdsemnmlgdrsbywlid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsa2RzZW1ubWxnZHJzYnl3bGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQ1OTksImV4cCI6MjA2NTM0MDU5OX0.NiUZFz4_27D1DkB9yHOep33TIYK__0fgtwCJtjWaH9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);